### ISSUE TITLE
CreateDev is never get called

### ISSUE THREAD

**Issue by immnas** [fulup-bzh/GeoGate#16]
Hi,
BackendStorage.prototype.CreateDev at file MongoDB-backend.js is never get called.
and due to that there is no "ALL_Devices" collections created.

also the variable this.logged at file _TcpClient.js is never set to "true".
it always not logged in.

I am trying to use following config for TK102 device .. 
Gps103   : {info: "Tk102 Gps103"    , adapter: "Gps103Tk102"   , port: 8090}

**Comment by immnas** [comment]
sorry my following line is not true.
" also the variable this.logged at file _TcpClient.js is never set to "true"."
but my first question is valid, CreateDev is never get called.

**Comment by fulup-bzh** [comment]
As it SHOULD be written in the readme !!! "CreateDev" should be call from telnet console before you can connect a new tracker. Connect with telnet on console and type "help" to get create command line. Expect for DummyBackend devices should be predeclared in DB before accepting inputs

Also note that it is true that I made a lot of modification since MongoDB backend was created and a significant part of the logic changed since that time. You may have to check MySql backend to align MongoDB with it.
